In [13]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [6]:
iris = load_iris()
x = iris.data
y = iris.target

print("Size of Training dataset:",x.shape)
print("Size of Training Target:",y.shape)

Size of Training dataset: (150, 4)
Size of Training Target: (150,)


In [7]:
x_train ,x_test ,y_train ,y_test = train_test_split(x,y,test_size = 0.3)

print("Size of Training data :",x_train.shape)
print("Size of Training target :",y_train.shape)

print("Size of Testing data :",x_test.shape)
print("Size of Testing target :",y_test.shape)

Size of Training data : (105, 4)
Size of Training target : (105,)
Size of Testing data : (45, 4)
Size of Testing target : (45,)


In [14]:
knn_model = KNeighborsClassifier()
knn_model.fit(x_train,y_train)
pred = knn_model.predict(x_test)
print(pred)

[1 2 0 0 0 0 0 0 2 1 2 1 1 0 1 1 2 2 0 2 0 2 0 1 1 2 0 0 1 1 1 1 2 2 0 2 1
 1 2 1 1 2 2 1 1]


In [15]:
print("Accuracy of training data:",accuracy_score(y_train,knn_model.predict(x_train)))
print("Accuracy of testing data:",accuracy_score(y_test,knn_model.predict(x_test)))
print("Confusion matrix of training data:",confusion_matrix(y_train,knn_model.predict(x_train)))
print("Confusion matrix of testing data:",confusion_matrix(y_test,knn_model.predict(x_test)))

Accuracy of training data: 0.9809523809523809
Accuracy of testing data: 0.9777777777777777
Confusion matrix of training data: [[37  0  0]
 [ 0 30  1]
 [ 0  1 36]]
Confusion matrix of testing data: [[13  0  0]
 [ 0 18  1]
 [ 0  0 13]]


In [1]:
import numpy as np
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
x = iris.data
y = iris.target

print("Shape of Training dataset:",x.shape)
print("Shape of Testing dateset:",y.shape)

Shape of Training dataset: (150, 4)
Shape of Testing dateset: (150,)


In [5]:
x_train,x_test,y_train ,y_test = train_test_split(x,y,test_size=0.3, random_state=109)
print("Shape of training dataset:",x_train.shape)
print("Shape of training dataset:",y_train.shape)
print("Shape of testing dataset",x_test.shape)
print("Shape of testing dataset",y_test.shape)

Shape of training dataset: (105, 4)
Shape of training dataset: (105,)
Shape of testing dataset (45, 4)
Shape of testing dataset (45,)


In [6]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
predict = knn.predict(x_test)

In [8]:
print("Accuracy of training dataset:",accuracy_score(knn.predict(x_train),y_train))
print("Accuracy of testing dataset:",accuracy_score(knn.predict(x_test),y_test))

print("Confusion matrics of training dataset:\n",confusion_matrix(knn.predict(x_train),y_train))
print("Confusion matrics of testing dataset:\n",confusion_matrix(knn.predict(x_test),y_test))

Accuracy of training dataset: 1.0
Accuracy of testing dataset: 0.9111111111111111
Confusion matrics of training dataset:
 [[38  0  0]
 [ 0 33  0]
 [ 0  0 34]]
Confusion matrics of testing dataset:
 [[12  0  0]
 [ 0 15  2]
 [ 0  2 14]]
